# Site settings
title: Captain
header-img: img/home-bg.jpg
email: gswang001@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: ""
# twitter_username: SBootstrap
github_username:  anytimekaka
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
